return {
	-- A list of parser names, or "all" (the five listed parsers should always be installed)
	ensure_installed = {
		"c",
		"lua",
		"vim",
		"vimdoc",
		"query",
		"astro",
		"git_config",
		"git_rebase",
		"html",
		"javascript",
		"jsdoc",
		"json",
		"json5",
		"latex",
		"markdown",
		"markdown_inline",
		"prisma",
		"python",
		"svelte",
		"toml",
		"tsx",
		"typescript",
		"yaml",
	},
	modules = {},
	ignore_install = {},
	sync_install = false,
	auto_install = true,
	indent = {
		enable = true,
	},
	highlight = {
		enable = true,
		additional_vim_regex_highlighting = false,
	},
}
